// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeGHHNsOPCL15T4KqysAjgK8UsZBi0CQk',
    appId: '1:1055546313423:web:498dba7a134213021505ba',
    messagingSenderId: '1055546313423',
    projectId: 'stripesetupproject',
    authDomain: 'stripesetupproject.firebaseapp.com',
    storageBucket: 'stripesetupproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2K_SFGuLMqQQlGZZu_fY1GMh4XZBMWU',
    appId: '1:1055546313423:android:59502a1952e52db01505ba',
    messagingSenderId: '1055546313423',
    projectId: 'stripesetupproject',
    storageBucket: 'stripesetupproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjsyeg7tndNDfyjY0SAFrI-53bernax8',
    appId: '1:1055546313423:ios:23846e48b179ff2c1505ba',
    messagingSenderId: '1055546313423',
    projectId: 'stripesetupproject',
    storageBucket: 'stripesetupproject.appspot.com',
    androidClientId: '1055546313423-27uq6m2gmk3euseq351rgc9k54gh88qj.apps.googleusercontent.com',
    iosClientId: '1055546313423-moif04f6t8ipmavh05bf5fr4fun6dlpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplicationInFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEjsyeg7tndNDfyjY0SAFrI-53bernax8',
    appId: '1:1055546313423:ios:23846e48b179ff2c1505ba',
    messagingSenderId: '1055546313423',
    projectId: 'stripesetupproject',
    storageBucket: 'stripesetupproject.appspot.com',
    androidClientId: '1055546313423-27uq6m2gmk3euseq351rgc9k54gh88qj.apps.googleusercontent.com',
    iosClientId: '1055546313423-moif04f6t8ipmavh05bf5fr4fun6dlpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplicationInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeGHHNsOPCL15T4KqysAjgK8UsZBi0CQk',
    appId: '1:1055546313423:web:8a871c83b03c496f1505ba',
    messagingSenderId: '1055546313423',
    projectId: 'stripesetupproject',
    authDomain: 'stripesetupproject.firebaseapp.com',
    storageBucket: 'stripesetupproject.appspot.com',
  );

}